name: builds
on:
  push:
    branches:
      - main
      - main-preview

jobs:
  build_local:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: localdev-root-password
          MYSQL_DATABASE: codex

          MYSQL_USER: localdev-user
          MYSQL_PASSWORD: localdev-password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup env.properties
        run: |
          echo "DB_URL=jdbc:mysql://localhost:3306/codex" >> src/main/resources/env.properties
          echo "DB_USERNAME=localdev-user" >> src/main/resources/env.properties
          echo "DB_PASSWORD=localdev-password" >> src/main/resources/env.properties

      - name: Cache packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build
        run: mvn clean package
